### ISSUE TITLE
Discord Rich presence and last.fm tracking not working

### ISSUE THREAD

**Issue by n-xsi** [SpotX-Official/SpotX#155]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://github.com/amd64fox/SpotX/discussions/111#discussion-4304353">described in the FAQ</a>

### Сountry of your account

United Kingdom

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.1.94.870.gf994cb0b
- Windows: Windows 10 21H2 19044.2006
- PowerShell: 5.1.19041.1682
```

### 📝 Description

After installing SpotX, Neither Discord rich presence or last.fm tracking are working. I've tried reinstalling and still got the same issue.
